fix(parent/child): Add host argument to parent and child factories.
hybridsjs/hybrids pull request #188
Opened 2022-02-18 23:21 UTC by auzmartist

Hi @smalluban!

Here's a totally unsolicited (but helpful) feature which you might find complementary to the existing parent/children factories...

For some complex components which reference parent and child elements based on element context, access to the host element is helpful. This can be done without a breaking change and creates some options for advanced component interactions.

For example, to get a parent which exposes a particular property name:

```js
const MyChildComponent = define({
  tag: 'my-child-component',
  context: '__ctx__',
  contextProvider: parent((el, {context}) => el.hasOwnProperty(context)),
  // ...
})
```

Another use case:

```js
const ChildElementCounter = define({
  tag: 'child-element-counter',
  childTag: '',
  children: children((el, {childTag}) => el.tag.toLowerCase() === childTag),
  // ...
})
```

Have a look and let me know what you think. Thanks! 👍

2022-02-24 11:41 UTC, smalluban requested changes
Hi @auzmartist!

Thanks for your time in creating this PR. At first, i thought that it might be a not really useful feature, or it even might not work as you expect it, but after looking at this for a while, I can't make a reasonable argument against it.

I will merge the feature, but we need some changes:
* Create tests where the value from `host` changes, so the children/parent is updated (as null, or an empty array)
* there is API reference in docs, please update it as well

2022-02-25 00:38 UTC, auzmartist commented
Alright, I've added a couple more tests and added to the API docs. Ready for re-review @smalluban. 👍

2022-02-25 08:46 UTC, smalluban approved these changes

2022-02-25 08:46 UTC, merged

2022-02-25 08:46 UTC, smalluban commented
Nice work, thanks!